#!/bin/sh

# Start essential programs
sxhkd &

# Set Atom One Dark-like colors for bspwm
# Base colors
FOREGROUND="#ABB2BF"
BACKGROUND="#282C34"
BLACK="#282C34"
RED="#E06C75"
GREEN="#98C379"
YELLOW="#E5C07B"
BLUE="#61AFEF"
MAGENTA="#C678DD"
CYAN="#56B6C2"
WHITE="#ABB2BF"

# Set bspwm colors
bspc config normal_border_color "$BLACK"
bspc config active_border_color "$BLUE"
bspc config focused_border_color "$BLUE"
bspc config presel_feedback_color "$GREEN"

# Apply default theme (dark)
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface gtk-theme 'Nordic'
gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'

# Start picom compositor
picom &

# Start Notifications Dunst
dunst &

# Set wallpaper
feh --bg-fill --randomize ~/Pictures/wallpaper/* &

# Kill existing polybar instances
killall -q polybar
# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
# Launch polybar
polybar main &

# Start greenclip if not already running
pgrep -x greenclip || greenclip daemon &

# Monitor settings
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Global settings
bspc config border_width         4
bspc config window_gap          10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Window rules
bspc rule -a firefox desktop='^2'
bspc rule -a markdown_cheatsheet state=floating sticky=on center=true rectangle=800x600+0+0
bspc rule -a Pavucontrol state=floating center=true
bspc rule -a Zotero desktop='^3'
bspc rule -a obsidian desktop='^4'
bspc rule -a Slack desktop='^5'
bspc rule -a Signal desktop='^5'
bspc rule -a Spotify desktop='^8'
# bspc rule -a org.gnome.Nautilus state=floating center=true
